### ISSUE TITLE
Remove hackforums

### ISSUE THREAD

**Issue by duraki** [vitalysim/Awesome-Hacking-Resources#111]
LOL srsly?

**Comment by dukeofdisaster** [comment]
The entire point of this repo is to curate resources where people can learn, with lean towards free resources; while I assume that you're raising the issue because you disapprove of hackforums shady side, the fact remains that it's a free resource. @vitalysim I vote for closing this issue without removal.

**Comment by vitalysim** [comment]
@dukeofdisaster  I agree with you.

The issue is closed!
